### ISSUE TITLE
aws.ec2_describe_instances doesn't accept InstanceIds argument in workflow

### ISSUE THREAD

**Issue by davbera** [StackStorm-Exchange/stackstorm-aws#110]
A workflow executing aws.ec2_describe_volumes specifying InstanceIds as parameter issues an error. 

**my_workflow.yaml**
....
tasks:
  task1:
    action: aws.ec2_describe_instances InstanceIds="i-XXXXXXX"
....

`$ st2 run awsec2mngmt.my_workflow`
id: ....
action.ref: awsec2mngmt.my_workflow
parameters: None
status: failed
start_timestamp: Tue, 21 Jul 2020 18:18:54 UTC
end_timestamp: Tue, 21 Jul 2020 18:18:55 UTC
result:
  errors:
  \- message: 'SyntaxError: unexpected EOF while parsing (<unknown>, line 1)'
    route: 0
    task_id: task1
    type: error
  output: null

However, workflow works if InstanceIds is not specified
**workflow.yaml**
....
tasks:
  task1:
    action: aws.ec2_describe_instances
....

The following also works:
`$ st2 run aws.ec2_describe_instances InstanceIds="i-XXXXXXX"`

Same for ec2_describe_volumes

Thank you

**Comment by amanda11** [comment]
I think instanceIds is an array - could you try
InstanceIds = ["i-xxxxxx"]

**Comment by davbera** [comment]
Thank you, @amanda11 !

It's working perfectly. Trust me I tried a lot of things except this one... Sorry about it

**Comment by amanda11** [comment]
@davbera No worries - happy to help.
