### ISSUE TITLE
Need ability to execute aws pack actions to different AWS accounts/regions

### ISSUE THREAD

**Issue by k-willowhawk** [StackStorm-Exchange/stackstorm-aws#112]
I have a primary use case where I want to use orchestration through ST2 to carry out actions in different AWS accounts or regions, which will require being able to override the pack-configured access key and secret key, or the region, or both.

I don't see a method to do this built into the actions, and there doesn't seem to be any way to override these values short of writing out to a aws-cli config/credentials pair and running core.local actions instead of using this fine pack.

Thoughts?

**Comment by blag** [comment]
This timing is really good.

For future travelers, here is some reading material, in order:

1. [StackStorm forum post about multi profiles](https://forum.stackstorm.com/t/pack-configs-different-hosts-credentials/398/12), including a discussion about security implications and different implementation strategies
2. Prior art in the [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html)
3. [PR implementing multiple profiles for the Jira pack](https://github.com/StackStorm-Exchange/stackstorm-jira/pull/19) - ran into a bug in StackStorm config parsing that broke this PR
4. [PR hopefully fixing the StackStorm config parsing bug](https://github.com/StackStorm/st2/pull/5225)

@k-willowhawk I see you found the forum post. Would you be interested in drafting a PR for this pack implementing multiple profiles?

I'm not going to have time to circle back around to this for at least another month or two.

**Comment by amanda11** [comment]
Please also note that the aws-boto3 pack already supports multi-region support. So migrating from the aws to the aws-boto3 pack also allows AWS commands to be run across multi-regions: https://github.com/StackStorm-Exchange/stackstorm-aws_boto3

**Comment by k-willowhawk** [comment]
@amanda11 thank you, that was exactly what I needed.  I at first dismissed the `boto3` pack because I didn't understand it, and it appeared to only have a few actions vs. the thousands of actions in the `aws` pack.  Now I see that it really has two actions... AssumeRole and Boto3Action, which when used in concert, do exactly what I needed.   We can close this issue.

@blag since the aws-boto3 pack is a cleaner and more scalable implementation, I'm converting my workflows to leverage it.  I spent some time learning Python over the last week to understand what it was doing, and after testing it out outside of ST2, I understand the power and simplicity of it.
