### ISSUE TITLE
Actions fail when configured using new `pack config`.

### ISSUE THREAD

**Issue by dzimine** [StackStorm-Exchange/stackstorm-aws#22]
Scenario:
- install fresh st2 2.3dev
- `pack install aws`
- `pack config aws` (do configuration)
- try AWS action. *Bummer 1: Unable to locate credentials*
- rm `packs/aws/config.yaml` to avoid confusion
- try AWS action. *Bummer 2: KeyError: st2_user_data*

Problems: 
1) `config.yaml` is conflicting with new config, time to completely migrate.
2) https://github.com/StackStorm-Exchange/stackstorm-aws/blob/master/actions/lib/action.py#L26-L30 This leads to `KeyError` when user data not set. Pls account.
3) example config needs validation against config schema in CI.

**Comment by userlocalhost** [comment]
Thank you for the reporting.

I confirmed that your last scenario is reproduced.

I'll correct it including test-case.

**Comment by Kami** [comment]
@userlocalhost Thanks - you rock :)

On a related note - it would also be good to add a sample config when doing that (`aws.config.yaml.example`) because sample config gets validated against schema on CI so it could also help us catch some config (schema) related issues in the future.

**Comment by userlocalhost** [comment]
Thank you for your comment. I got it.

**Comment by LindsayHill** [comment]
Pack has been completely migrated to new config
