### ISSUE TITLE
Receive event for new EC2 instance

### ISSUE THREAD

**Issue by ksemba** [StackStorm-Exchange/stackstorm-aws#47]
I'm looking for a way to receive an event when a new EC2 instance has been created. I saw the high level info on https://github.com/stackstorm-exchange/stackstorm-aws#servicenotificationssensor but that doesn't give me any details on how to actually get this working.

At this point I don't mind using either SNS or SQS...whatever works ;)

An alternate method would be to pull all instances using the corresponding describe method ...but I'd like to implement an event driven approach here.

Any help would be highly appreciated.
Kurt

**Comment by warrenvw** [comment]
![screen_shot_2017-08-08_at_6 49 10_pm_720](https://user-images.githubusercontent.com/9972858/29238187-32914474-7ee4-11e7-8354-b87249ddc481.png)

@ksemba Based on my investigation, i would also be inclined to use the SQS sensor. you can subscribe your queue to an SNS topic. See the bottom selection in the Queue Actions menu. Let me know if you have any further questions and I'll do my best to help you out.

In the `/opt/stackstorm/configs/aws.yaml` file, specify the `aws_access_key_id`, `aws_secret_access_key`, `region`, `sqs_sensor/input_queues` and `sqs_other/max_number_of_messages` per the default config.
 
I've verified this works as expected.

I'll close this issue now, please re-open if necessary.

**Comment by ksemba** [comment]
Thank you @warrenvw
