### ISSUE TITLE
Using payload information in action

### ISSUE THREAD

**Issue by thodav** [StackStorm-Exchange/stackstorm-aws#69]
It seems like it isn't possible to use payload information for action automation.

Specifically I use a Sensor to obtain information about EC2 instances and want to dynamically use the instance id stored in the payload to perform an action.

In the criteria field it even suggests the payload key (trigger.payload_instanceId), unfortunately this isn't working in the InstanceIds input field of the AWS integration pack, as it takes the key name as a string and not the corresponding value.

------------
Edit:
Just realized this is a general issue and not just AWS related. Passing parameters from the payload to the action doesn't seem to be possible (at least if using the web GUI)

**Comment by LindsayHill** [comment]
Can you provide some examples of payload content and your rule here?

At a guess, your Jinja syntax is wrong

**Comment by LindsayHill** [comment]
Tracking this at https://forum.stackstorm.com/t/aws-action-instance-id-from-payload/303/3
